### ISSUE TITLE
results presentation vs project presentations

### ISSUE THREAD

**Issue by mallory** [eckelcu/draft-ietf-shmoo-hackathon#30]
In the first paragraph of 2.2. "the results presentation" is mentioned but this phrase hasn't been used in the text so far. In the agenda "project presentations" is listed. Perhaps best to harmonise this language. Additionally in 2.2 there could be a parenthetical reference to the later section 5.4.3.

**Comment by mallory** [comment]
Seeing now an additional section under 4.2. and because of inconsistent naming it didn't jump out to me in the TOC. Just additional evidence that there should be some harmonisation of terminology here. FWIW I like all of the terms, but there should be an official term for referencing, titling and subtitling purposes.

**Comment by eckelcu** [comment]
Good idea. I tried to align around consistent use of the term "project results presentation", which is sometimes shortened to "results presentation" or simply "presentation" provided there is enough context for the association to be clear. Please have a look at the PR and let me know what you think. Thanks.
